# Generated by Django 4.2.10 on 2024-05-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num_guest', models.IntegerField(max_length=20)),
                ('booking_date', models.DateField()),
            ],
        ),
    ]
